### ISSUE TITLE
Roadmap. List of top level tasks

### ISSUE THREAD

**Issue by ddrozdik** [drupal-ukraine/dmaps#9]
Here will be list of tasks ... For each task should be created an issue and linked with item in this list.
- [ ] Add Location Settings pages
- [ ] Add Location content type fields  
- [ ] Create Services described here https://github.com/drupal-ukraine/dmaps/issues/3
- [ ] Convert hook_help()
- [ ] Convert hook_permissions()
- [ ] ...
- [ ] Migration from D7 to d8
